import "./globals.css";
import type { Metadata } from "next";
import { Inter, Konkhmer_Sleokchher } from "next/font/google";
import { I18nProvider } from "@/providers/I18nProvider";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

const konkhmer = Konkhmer_Sleokchher({
  weight: "400",
  subsets: ["khmer"],
  variable: "--font-konkhmer",
});

export const metadata: Metadata = {
  title: "LS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${konkhmer.variable}`}>
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
